Update push.yml

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -15,10 +15,20 @@ jobs:
       - uses: actions/checkout@v3
         with:
           fetch-depth: 0
-      
+
+      - name: Install Dependencies
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y curl tar
+
       - name: Lokalise CLI
         run: |
-          curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh
+          echo "Installing Lokalise CLI..."
+          curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh -s -- v3.0.2
+          if [ $? -ne 0 ]; then
+            echo "Failed to install Lokalise CLI. Exiting."
+            exit 1
+          fi
 
       - name: Push Translations to Lokalise
         env:
@@ -33,10 +43,10 @@ jobs:
           fi
           for file in $MODIFIED_FILES; do
             if [ -f "$file" ]; then
-              ./bin/lokalise2 --token a911e0108d0d4e39c2418b454cce59c71958acb6 \
-                --project-id 697988836797282a57d412.26117221 \
+              ./bin/lokalise2 --token $VAR_LOKALISE_API_TOKEN \
+                --project-id $VAR_LOKALISE_PROJECT_ID \
                 file upload --file="$file" \
-                --lang-iso en \
+                --lang-iso $ENV_LOKALISE_SOURCE_LANG_ISO \
                 --replace-modified --include-path --use-automations=true \
                 --cleanup-mode --poll-timeout 120s
             fi
